### ISSUE TITLE
[Security] GET method on donation endpoints should use `user_id` in cookie rather than query param

### ISSUE THREAD

**Issue by nickhsine** [twreporter/go-api#209]
### Current Situation 
`/periodic-donations/:id`
`/donations/prime/:id`
`/donations/others/:id`
are using `user_id` query param.
For example, the client would send the GET method request like following
```
Headers:
  Cookie: id_token=<id_token>
  Authorization: Bearer <access_token>

Endpoint:
  `https://go-api.twreporter.org/v1/periodic-dontaions/10?user_id=1`
```

Even though we uses `middlewares/jwt.go` `ValidateAuthentication` and `ValidateAuthorization` to valid the request. However, we are only checking `donation.userID == c.Query('user_id')`, not checking `donation.userID == user_id in the access_token.payload`.
Therefore, hackers can send malicious requests to get others' donation data.

### Solution
Drop `user_id` query param.
Use `user_id in the access_token.payload` to validate the authorization.
